### ISSUE TITLE
SW-Lib and Caching Strategies.

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-helpers#113]
## Use Cases to Cover

1. Easily use a caching strategy for a route
1. Customise the behaviors for a caching strategy

## Easily Using a Caching Strategy

Options:

    goog.swlib.router.registerRoute('/', goog.swlib.fastest);
    goog.swlib.router.registerRoute('/', goog.swlib.strategies.fastest);
    goog.swlib.router.registerRoute('/', new goog.swlib.Fastest());
    goog.swlib.router.registerRoute('/', new goog.swlib.strategies.Fastest());

This would use a default cache for caching and would not use the precached assets.

- Should we make the precached assets available to runtime caches by default?

## Customise the Behaviors of Caching Strategy

Options:

    const behaviors = [.....];
    goog.swlib.router.registerRoute('/', goog.swlib.fastest, behaviors);
    goog.swlib.router.registerRoute('/', new goog.swlib.Fastest(behaviors));

Put like this, I'm leaning more toward making developers to instantiate the cache strategies.

Then only question is goog.swlib.strategies.* vs having members directly on goog.swlib.*.

@addyosmani @jeffposnick thoughts? Any other use cases?

**Comment by jeffposnick** [comment]
Passing in a `behaviors` array is unfortunately not enough to configure everything, since [`cacheName` is set on `RequestWrapper` independent of `behaviors`](https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-runtime-caching/src/lib/request-wrapper.js#L35). (There are also `fetchOptions` and `matchOptions` that could be configured, but there isn't a direct equivalent to that in `sw-toolbox`, so they're not as important here.)

So we'd need to either accept an already-constructed `RequestWrapper` instance as the third parameter, or we'd need to allow developers to pass in both `cacheName` and `behaviors` as parameters, or we could just give up on that approach and require that developers pass in an already-configured handler in as the second parameter.

I think my vote is for an interface that accepts both `cacheName` and `behaviors` in an object as the third parameter, since that could just be passed as-in directly to the `RequestWrapper` constructor. The second parameter could be a reference to a runtime caching class (not an instance of the class).

E.g.

```js
// No configuration; just use the default `new RequestWrapper()` under the hood:
goog.swlib.router.registerRoute('/', goog.swlib.fastest);

// Only configure cache name:
goog.swlib.router.registerRoute('/images/(.*)', goog.swlib.cacheFirst, {cacheName: 'image-cache'});

// Full configuration:
goog.swlib.router.registerRoute('/api/(.*)', goog.swlib.networkFirst, {
  cacheName: 'api-cache',
  behaviors: [new goog.cacheExpiration.Behavior({maxEntries: 10})]
});
```

So the syntax would effectively be a shorthand for constructing your own `RequestWrapper` and using it to instantiate a runtime caching class. There's some risk of falling to the same "configuration is done via a random Object with random properties" trap that plagued `sw-toolbox`, but at least the third parameter maps directly to the `RequestWrapper` constructor's parameters, and there's validation done there. It's less of a black box.

In this model, `goog.swlib.networkFirst`, etc. are just lightweight aliases to the actual `goog.runtimeCaching.*` classes, to save developers the trouble of having to import that module directly.

**Comment by gauntface** [comment]
Playing devils advocate a little bit:

Why not have something following these lines:

    goog.swlib.router.registerRoute('/api/(.*)', goog.swlib.networkFirst({
        cacheName: 'api-cache',
        maxEntries: 10,
    }));

My main thinking here is that we can configure the caching strategies as the function is called, the options are clearly tied to the caching strategy instead of the being tied to the route and / or caching strategey and it the remove the need to understand behaviors.

For developers that may need to customise the behaviors we can either require the pass in a custom handler OR we allow a seperate behaviors array:

    goog.swlib.router.registerRoute('/api/(.*)', goog.swlib.networkFirst({
        cacheName: 'api-cache',
        maxEntries: 10,
        behaviors: [......]
    }));

@addyosmani @jeffposnick thoughts on this?

**Comment by jeffposnick** [comment]
I can see the appeal of that. But rather than having the runtime caching strategies behave differently when used via `sw-lib`, we could just make some changes to the underlying definitions inside of `sw-runtime-caching` and then everyone would benefit from less `RequestWrapper` overhead.

The constructor for the `Handler` class, used by all these runtime caching strategies, [currently looks like](https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-runtime-caching/src/lib/handler.js):

```js
constructor({requestWrapper} = {}) {
  if (requestWrapper) {
    this.requestWrapper = requestWrapper;
  } else {
    this.requestWrapper = new RequestWrapper();
  }
}
```

We could change that to:

```js
constructor(args = {}) {
  if (args.requestWrapper) {
    this.requestWrapper = args.requestWrapper;
  } else {
    this.requestWrapper = new RequestWrapper(args);
  }
}
```

This would allow code like

```js
goog.swlib.router.registerRoute('/api/(.*)', goog.swlib.networkFirst({
  cacheName: 'api-cache',
  behaviors: [...]
}));
```

to Just Work.

I'm less positive about the other part of your suggestion, which would check for a `maxEntries` configuration option and then automatically configure and use a corresponding `goog.cacheExpiration.Behavior`.

There are theoretically going to be a lot of useful behaviors that developers might want to configure, and I'm not sure about how we could keep track of which options correspond to which behavior. What if both `goog.cacheExpiration.Behavior` and `goog.backgroundSyncQueue.Behavior` support a `maxEntries` option? There's a lot of potential for ambiguity.

**Comment by gauntface** [comment]
The reasoning for the maxEntries in the top level object is we need to draw a line between when the high level library is smoothing the API and when it expects the developer to use the seperate modules.

Having `maxEntries` would be just a smoothing other and regarding "multiple maxEntries" the sw-lib library would be doing the plumbing, so it wouldn't support the bgSync behavior, that would need to be done through the additional behaviors.

From my example, your version would be:

    goog.swlib.router.registerRoute('/api/(.*)', goog.swlib.networkFirst({
      cacheName: 'api-cache',
      behaviors: [new goog.swlib.CacheExpiration({maxEntries: 10})]
    }));

It's largely boilerplate compared to `maxEntries` and arguably, maxEntries and maxSize are common enough that they could warrant special treatment.

**Comment by jeffposnick** [comment]
> arguably, maxEntries and maxSize are common enough that they could warrant special treatment.

It's definitely a judgment call, and I guess I come down on the other side of that argument. We may end up only reinforcing the use cases that were possible with `sw-toolbox` if we give those options special treatment, leading to situations in which the cool new stuff like background queueing or the Broadcast Channel API announcements don't get used.

@addyosmani, do you have any thoughts?

**Comment by gauntface** [comment]
To support new behaviors, I would expect the developer to use behaviors.

    // Default case:
    goog.swlib.router.registerRoute('/api/(.*)', goog.swlib.networkFirst({
        cacheName: 'api-cache',
        maxEntries: 10,
    }));

    // Exceptional case:
    goog.swlib.router.registerRoute('/api/(.*)', goog.swlib.networkFirst({
        cacheName: 'api-cache',
        maxEntries: 10,
        behaviors: [
            new goog.backgroundSyncQueue.Behavior({maxEntries: 10})
        ]
    }));

But yeah @addyosmani your input here would be useful.

**Comment by jeffposnick** [comment]
Here's another option that splits the difference: use a unique identifier for each behavior class , and then pass in the configuration as you'd normally pass it in to the behavior's constructor. `SWLib` would take care of actually constructing the behaviors.

This requires maintaining a mapping between "known" behaviors and the unique identifier used in `SWLib` (e.g. `cacheExpiration` ➡️ `goog.cacheExpiration.Behavior`, `broadcastCacheUpdate` ➡️ `goog.broadcastCacheUpdate.Behavior`, etc.), but that's not too hard to maintain. And we'd still support taking in manually constructed behaviors via `behaviors: [...]`.

So that would look like:

```js
// Use the defaults:
goog.swlib.router.registerRoute('/api/(.*)', goog.swlib.networkFirst());

// Maximal configuration:
goog.swlib.router.registerRoute('/api/(.*)', goog.swlib.networkFirst({
  cacheName: 'api-cache',

  cacheExpiration: {
    maxEntries: 10,
    maxAgeSeconds: 60 * 60
  },

  broadcastCacheUpdate: {channelName: 'api-updates'},

  behaviors: [/* anything extra */]
}));
```

**Comment by gauntface** [comment]
I can't work with the last one, seems a fair compromise.

**Comment by jeffposnick** [comment]
You wrote "I **can't** work with the last one..."; did you mean **can**? I think so, but just wanted to make sure we were on the same page.

I'm sold on the value of using `SWLib` with this syntax: you get nice shortcuts for what would otherwise be a repetitive process of creating `RequestWrappers` and multiple behavior classes.
