### ISSUE TITLE
Support custom cache handlers

### ISSUE THREAD

**Issue by samuelli** [GoogleChrome/sw-helpers#131]
When building out webcomponents.org we ran into a few interesting use cases which were difficult to handle. There were particular custom HTTP status codes we would return for different 'failure' states.

There was another case where the request/response don't result in an error, per se, but we still didn't want to cache the response. Use case was that our site supported publishing and while everything 'works', we wanted to expose an error in the process that was performed so we returned this in the response body. This would get incorrectly cached simply because the status code was 200.

Status: 200
Body:
{ error: 'some process error' }

**Comment by jeffposnick** [comment]
Hello @samuelli—We're definitely thinking of that use case. `sw-toolbox`'s system of providing a RegExp for status codes to determine cacheability worked, to some extent, but wasn't as flexible as it could be.

What we have done so far with `sw-helpers` is to introduce a pluggable behavior system to customize the request/caching/response flow. There's a specific callback that gets automatically invoked by our `RequestWrapper` middleware, called `isResponseCacheable`, which gets to take a look at the response and determine whether or not it should be used to update the cache.

You can see one behavior implementation at https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-cacheable-response-behavior/src/lib/behavior.js#L48, which makes it easy for developers to specify which status codes and/or header values they want to check to determine whether a response should be cached.

Giving developers the option of checking the response body inside the `isResponseCacheable` callback would take some additional changes, in that we'd need to make it an `async` method, since getting the body of a response can only be done asynchronously (and only done on a clone of the original `Response` object). If checking the body is important to you—if you can't rely on checking a header synchronously, for instance—then we should be able to make that change. Let me know if examining response bodies is absolutely required.

**Comment by samuelli** [comment]
@jeffposnick: SGTM.

Checking the header may be sufficient, we could probably insert info in the header similar to normal browser caching headers.

Maybe its worth considering a special "no-sw cache" header that's respected by default. Similar to how servers already defining caching rules which browsers respect, there's cases where its easier to define whether or not a response should be cached on the server side of a request (it already had to analyse the request) instead of doubling that work on the client and also dealing with versioning & sw versioning.

**Comment by samuelli** [comment]
Maybe also just a flag to respect regular caching headers for a request?

**Comment by jeffposnick** [comment]
I'd hesitate to try to replicate in JavaScript the logic that's needed to fully interpret HTTP caching headers, as I have a feeling that covering all the edge cases could be tricky, and it could wrongly confuse folks into thinking that any `max-age` values would automatically configure cache expiration.

As long as you're cool with a headers-based approach, you should be able to do the following, and get full flexibility in implementing the logic you want:

```js
const myCacheableCheck = {
  cacheWillUpdate: ({response}) => {
    // Or implement whatever other logic you want, e.g. check for 'x-no-sw: true'
    return response.headers.get('cache-control') !== 'no-cache';
  };
};

const requestWrapper = new goog.runtimeCaching.RequestWrapper({
  cacheName: 'my-cache',
  behaviors: [myCacheableCheck],
});

const route = new goog.routing.RegExpRoute({
  regExp: new RegExp('^https://example.com/api/'),
  handler: new goog.runtimeCaching.StaleWhileRevalidate({requestWrapper}),
}); 

const router = new goog.routing.Router();
router.registerRoute({route});
```

(That all is very low-level; there will be helpers in the [`sw-lib` project](https://github.com/GoogleChrome/sw-helpers/tree/master/packages/sw-lib) that provide shortcuts for setting up request wrapper and routes, which should lead to a more `sw-toolbox`-like syntax.)

**Comment by gauntface** [comment]
I'm going to close this for now - please reopen if anyone feels this isn't a solution they can use.
