### ISSUE TITLE
sw-lib Change cacheName

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-helpers#134]
- [ ] If the developer wanted to change where revisioned files are cached, how would they do it? At the moment the API doesn't allow it in sw-lib.
- [ ] If I didn't set a cache name and then decided I wanted to, will the new cache copy over old requests? Would the old cache be automatically deleted? Does this apply to both revisioned and unrevisioned?

**Comment by jeffposnick** [comment]
Modifying the name of an existing revisioned file cache seems super edge case-y to me. Maybe there's some reason I'm overlooking, but doesn't seem like something to prioritize.

If I did change the cache identifier, my inclination would be to not copy over the contents of the previous cache (assuming we could identify what the previous cache was), because I'd view changing the identifier as the developer intending to start fresh.

You can't really infer that any cache whose name matches a given pattern on the origin is going to be an older version of the revisioned cache, because it's common for developers to, for example, serve bunch of different development builds off of `localhost:8000`, and use different cache identifiers to keep cached material separate. If we tried to make guesses about whether other caches were old version or completely separate, it would be easy to guess incorrectly.

**Comment by addyosmani** [comment]
> Modifying the name of an existing revisioned file cache seems super edge case-y to me. Maybe there's some reason I'm overlooking, but doesn't seem like something to prioritize.

It's unclear to me why you would want to rename a revisioned file cache that already exists. Surely it would be cleaner to clear the existing cache with revisioned files and create a fresh one rather than say, copying over the contents of the existing cache. It also feels like attempting to support something like that might be prone to breakage. 

Perhaps we keep this open for discussion in case there's an edge-case we are not seeing and can come back to it later?

**Comment by gauntface** [comment]
I'm going to close this issue and see if the request to change the cacheName comes up at the hackathon. I'm struggling to see the use case for it beyond a nice to have.
