### ISSUE TITLE
duplicate-entry-diff-revisions question

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/sw-helpers#142]
**Library Affected**:
*sw-precaching*

**Issue or Feature Request Description**:
Consider this an edge-case and if there's no action to be done here, feel free to ignore.

I attempted to use the `revisionedFiles` field to cache the same file path but with different revision numbers. I think my expectation was that the revision manager would check which revision number was highest and automatically handle that case for me. This might be out of scope or just difficult, especially if the `revision` field is a flexible string (rather than an integer) by default.

So this is what fails:

```js
const precacheManager = new goog.precaching.PrecacheManager();
precacheManager.cacheRevisioned({
  revisionedFiles: [
    {
      url: '/test.js',
      revision: '1234'
    },
    {
      url: '/test.js',
      revision: '1235'
    }
  ],
});
```

Exception:

```
Uncaught duplicate-entry-diff-revisions: An attempt was made to cache the same url twice with each having different revisions. This is not supported.
```

**Comment by gauntface** [comment]
The revision is just a string, it's not a number.

If you look at the revision output by the sw-cli it'll actually use the file hash for the revision (This is was sw-precache did).

In this case, failing is the only way to go since the revision isn't a numerical order, but rather some unique identifier to compare a file between service worker installs **not** a way of selecting which revision to install in this service worker.
