### ISSUE TITLE
The 'handler' parameter must be an object that exposes a 'handle' method.

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-helpers#152]
```javascript
swlib.router.registerRoute('/about', new swlib.Route({
  match: () => {
    console.log(arguments);
  },
  handler: {
    handle: () => {
      console.log('Handler about.');
    },
  },
}));
```

Either this is a bug or I'm being blind to the issue. Running this from sw-lib throws the error:

> The 'handler' parameter must be an object that exposes a 'handle' method.

**Comment by jeffposnick** [comment]
That looks like the right syntax to me. I'll dig in and see what the bug is.

**Comment by jeffposnick** [comment]
The issue is that you're passing in a `Route` as the second parameter to `registerRoute()`, which doesn't match the [expected parameters](https://github.com/GoogleChrome/sw-helpers/blob/e97bebda4b7e50873935a18d35b68bfb809479ab/packages/sw-lib/src/lib/router.js#L61).

Maybe you meant to pass in the `Route` as the first parameter? Or just pass in a `Handler`/`function` as the second parameter.
