### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by AshleyScirra** [GoogleChrome/sw-helpers#17]
As described in https://www.scirra.com/blog/ashley/27/service-workers-are-a-pain-in-the-ass, the difficult points of using SW to replicate appcache are:

- implicit caching of the index page (regardless of its precise name) including when just /
- reload-to-update (with the same browser window)
- atomic swaps (never mixes versions)

The documentation for sw-appcache-behavior does not seem to specifically address this. It would be reassuring to see it more comprehensively documented that it covers this, and if not, to have any exceptions listed.

**Comment by jeffposnick** [comment]
The library was written with the intention of matching App Cache behavior (almost[❋]) exactly, including what you mention. The lack of caveats about what the library *doesn't* match was intentional. I'd definitely welcome any bug reports with reproductions for instances where that's not the case, and I'll try to get those resolved.

(❋I'll probably implement a [max cache age of 24 hours](https://github.com/GoogleChrome/sw-helpers/issues/18) for the manifest file to work around a dangerous aspect of the App Cache spec, at which point I'll note that difference in the documentation.)

**Comment by jeffposnick** [comment]
So the [current docs](https://github.com/GoogleChrome/sw-helpers/tree/master/projects/sw-appcache-behavior#googappcachebehaviorfetch) are more explicit about how the library is supposed to provide equivalent behavior to AppCache, gotchas and all, with the exception of capping the cache lifetime of the manifest at 24 hours.

If there's any behavior that *doesn't* match AppCache, then it's likely a bug. If I can't work around the bug, I'll explicitly call it out in the documentation, but ideally, I'd just fix the bug.

(Have you tried out the library in any projects? Feedback is welcome.)
