### ISSUE TITLE
Support alternative cache key URLs in RequestWrapper.fetchAndCache

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#178]
CC: @gauntface 

**Library Affected**:
`sw-runtime-caching`

It could be useful to support passing in an additional optional parameter to [`RequestWrapper.fetchAndCache`](https://github.com/GoogleChrome/sw-helpers/blob/81fedc4a1183c6137d19c07800d806090df17ce3/packages/sw-runtime-caching/src/lib/request-wrapper.js#L177) allowing developers to provide an alternative cache key URL, if they don't want the `request.url` used.

The use case is when the `request` includes cache-busting URL parameters, which ideally wouldn't be used in the cache key.

The revised method signature could be:

```js
async fetchAndCache({request, waitOnCache, cacheKey}) {
  // ...
}
```

**Comment by gauntface** [comment]
Thanks for opening the issue. I'm happy to do this work if you want to
assign it to me.

**Comment by gauntface** [comment]
@jeffposnick I just started too look at the fetchAndCache and I have it implemented but one scenario I'm not sure how best to handle is when a response isn't ok.

If the response.ok is false, it shouldn't be cached (Unless 'behaviorCallbacks.cacheWillUpdate is defined).

If the entry isn't cached, are you happy to throw an error rather than continue without caching and returning the response? Thinking being that returning the response does not mean it wasn't cached.

**Comment by gauntface** [comment]
I ended up checking !cacheable && waitOnCache to determine if an error should be thrown (Means this method can be used in runtime caching strategies without any change in behavior).

**Comment by jeffposnick** [comment]
That seems like a reasonable compromise to me. I'll take a look at the PR!
