### ISSUE TITLE
Rename sw-cli or split?

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-helpers#207]
@addyosmani @jeffposnick 

Given the number of conversations that have come up, do you think it would be worth seperating out the build of sw and file manifest from the sw-cli?

- Makes it more natural to use `const swBuild = require('sw-build')` in build process
- Breaks things up into smaller modules like the rest of sw-helpers
- Means sw-cli can be freed up to do more (which generally I think is the direction everyone wants it to go in).

Thoughts?

**Comment by jeffposnick** [comment]
We have spent a lot of time focused on the `sw-cli` use case, and I think you're right in suggesting that focusing on the smaller bits first would be a good approach forward.

If the smaller bits (primarily manifest generation) were cleanly exposed in a standalone fashion, I'd pair it with a bundling process and hopefully end up with a recipe for a complete build solution that I'm happy with. And then I'd probably be less concerned about how `sw-cli` scaffolding things out.

**Comment by jeffposnick** [comment]
E.g. here's a hypothetical build process that seems reasonable to provide as a "recipe", and that I might use myself:

`service-worker.js`:
```js
import manifest from './build/manifest'; // This will be generated as part of the rollup build
import SWLib from 'sw-lib'; // This gets pulled in from node_modules

SWLib.cacheRevisionedAssets(manifest);

// Other SWLib methods to configure runtime caching, etc.
```

`rollup.config.js`:
```js
import resolve from 'rollup-plugin-node-resolve';
import swBuild from 'sw-build'; // Or whatever it's called.

swBuild({
  dest: './build/manifest.js',
  // other configuration options, similar to what's
  // supported in sw-precache today.
});

export default {
  entry: 'service-worker.js',
  dest: 'build/service-worker.js',
  format: 'iife',
  plugins: [resolve()]
};
```

It might make more sense to have that `swBuild()` step wrapped in a Rollup plugin, actually, rather than as code that runs as a "side-effect".

I think the Webpack usage would look similar, although in that case it might be a good idea to steer people towards creating a specific named entry for their `service-worker.js`, and then using a... loader(?) to make sure that the manifest was regenerated with the appropriate configuration? (My ignorance about Webpack best practices is showing.)

**Comment by gauntface** [comment]
Sounds like you are on board, will add it to my todo-list for the CLI.

**Comment by addyosmani** [comment]
> I think the Webpack usage would look similar, although in that case it might be a good idea to steer people towards creating a specific named entry for their service-worker.js, and then using a... loader(?) to make sure that the manifest was regenerated with the appropriate configuration? (My ignorance about Webpack best practices is showing.)

I've been noodling on how useful it would be for us to start fleshing out the Webpack plugin to accompany the new work. Given there are open questions about the regeneration and loading flow here, is this something we think is valuable to get done sooner rather than later to identify gaps or should it come after the beta milestone?

**Comment by gauntface** [comment]
I think we are there in terms of something minimal that can be used for this.

The node-module can be used to build working SW and build manifest. The CLI can still generate the SW but needs the manifest being added in.

Please please please try out the node module when you get a chance.

Going to close this for now - please open new issues if there are more specific conerns, issues or . . . . anything else I've messed up in this process.
