### ISSUE TITLE
How to "manually handle" with a Handler?

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-helpers#212]
cc @addyosmani @jeffposnick 

This is possible (I think) with the current API, but wanted to see if anyone else thought there could be a better API.

The scenario: "I have templates I've precached and / or desire to use caching strategies such as CacheFirst or StaleWhileRevalidate on. I want to retrieve these templates from the cache and / or network and manipulate them before returning them to the browser.".

This raises a few issues / concerns / comments:

1. If the assets are precached the cache name will need to be exposed in sw-lib if they were to use one of our caching strategies. [*NOTE:* Is there a way we could reduce to a single cache for precache and runtime caching?]
2. How should a developer use a caching strategy for this use case?

I started to just prototype something like this for my site where the request was always fetching from the network:
```
swlib.router.registerRoute('/', {
  handle: (details) => {
    if (details.event.request.mode !== 'navigate') {
      return;
    }

    const requiredTemplates = [
      `/home.json`,
    ];
    return Promise.all(
      requiredTemplates.map((templateUrl) => {
        return fetch(templateUrl).then((response) => response.json());
      })
    )
    .then((results) => {
      return new Response('<html><body>' + results[0].html + '</body></html>', {
        headers: {
          'Content-Type': 'text/html',
        },
      });
    });
  },
});
```

Replacing the fetch with something like CacheFirst, I imagine I'd do something like this (with today's API):

```
const cacheFirst = new CacheFirst();
cacheFirst.handle({
  event: {
    request: new Request('/home.json')
  }
})
.then((response) => {
   // DO STUFF
});
```

This feels clunky, just because of the "fake event" in this case.

In sw-toolbox I could do this (although reading this back it looks like an unusual side effect of the API - allow I may be over thinking it):

```
toolbox.cacheOnly(new Request(`/home.json`))
.then(response => {
  return response.json();
}),
```

One approach I like conceptually is adding some API to the router that would allow making a manual request and behind the scenes use the routing magic, so I would do the following:

```
router.fetch(new Request('/home.json'))
.then((response) => {
   // DO STUFF
});
```

and somewhere in my service worker I'd register a route for this request:

```
router.registerRoute('/home.json', new CacheFirst());
```

The benefit of this is that it adds a nice level of seperation from getting the template and how the template is stored. This may also allow picking up assets from the precache cache without the user needing to do anything.

p.s. Side note: One amazing thing about using the handler code in my personal site is that if I make an error in my code - it get's caught by the router and a network request is returned instead - AMAZING for sanity and a nice safety net.

**Comment by jeffposnick** [comment]
I've run into a similar use case with my own blog. But what I ended up doing was just relying on the Cache Storage API to retrieve the `Response`, rather than trying to "fake" things with a `fetch()`.

This was harder using `sw-precache`, since the cache keys included versioning info in their URLs, so i needed to create a [helper function](https://github.com/jeffposnick/jeffposnick.github.io/blob/work/src/lib/url-to-cache-key.js) which looked up the actual cache key, and then [passed that key into [`caches.match()`](https://github.com/jeffposnick/jeffposnick.github.io/blob/work/src/lib/network-file-system.js#L8). (It falls back to making a `fetch()` if there's no match for some reason, like the user manually cleared their cache.)

With the new precaching code, we're keeping versioning info in IDB and not in cache keys, and I thought the main motivation for that was so that this exact use case would be easier. You should just be able to `caches.match(myTemplateUrl)` and then use the `Response`, right? With `caches.match()` you don't even need to know the underlying cache name, just the URL.

**Comment by gauntface** [comment]
Yeah they can just use caches.matches() for precaching - you are right.

The remaining question is if we should support runtime caching strategies for this kind of use case.

**Comment by jeffposnick** [comment]
My gut answer to that question would be no, with a willingness to revisit if a use case come up that wasn't addressed cleanly via the Cache Storage API primitives.
