### ISSUE TITLE
Doc Needs for Hackathon

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-helpers#268]
cc @jeffposnick @addyosmani @jpmedley 

- [ ] Recipe for SW-CLI + NPM Publish Scripts
- [ ] Recipe for SW-Build + IIFE -> Gulp & Inlining
- [ ] Recipe for SW-Build + ES2015 Module -> Gulp & Rollup
- [ ] Guide to using sw-lib for runtime
- [ ] Document on the structure of sw-helpers.

Is there anything else we should be adding?

Do we want to bother changing to workbox and wb-* modules? This could help remove confusion with other sw-* libraries.

**Comment by jpmedley** [comment]
Is this the priority? I'm working on CLI+NPM unless I hear otherwise.

**Comment by jeffposnick** [comment]
Hey @jpmedley—As discussed at today's sync-up, I think the biggest gap that you could fill is on the narrative side of things, rather than producing specific recipes. On the recipe front, @gauntface, @prateekbh, and I all have snippets we could share based on our existing experiments.

The items on that list that scream "Joe!" to me would be "Document on the structure of sw-helpers." and "Guide to using sw-lib for runtime".

I think the workbox renaming has to happen sometime, but maybe after the hackathon.

**Comment by jpmedley** [comment]
Guide to sw-lib is in this: https://docs.google.com/document/d/1MC6pO3rF8g9op22YRD9thG2k-YWhOT1EUm5PkYXOhN0/edit#heading=h.z3mekvoay8yw

**Comment by jpmedley** [comment]
The phrase 'structure of sw-helpers' could mean several things. Can one of you please clarify this?

@jeffposnick @gauntface

**Comment by gauntface** [comment]
It's referring to the structure of this repo. I.e. if someone were to look at this Github Repo - they'll probably be lost as to what everything is for and how it fits together.
