### ISSUE TITLE
Feature Request: Include minified offline-google-analytics.js in npm install

### ISSUE THREAD

**Issue by deanhume** [GoogleChrome/sw-helpers#31]
**Library Affected**:
sw-google-offline-analytics

**Browser & Platform**:
All browsers

**Feature Request Description**:
It would be great if the npm install also included a minified version of the offline-google-analytics.js file 👍

**Comment by addyosmani** [comment]
@jeffposnick I'm personally in favor of us including minified/built distributables in the packages we release on npm, but curious what your thoughts were on this (some folks prefer to just stick to unbuilt for simplicity and encourage end-users to tackle minification themselves).

**Comment by gauntface** [comment]
The minified version is now the only version you can get. This is kind of a flip on this. Should we still include the "non-minified" version as well?

My general feeling on this has been we ship the minified version by default and offer a `.debug.js` version that is the rollup-'ified' version but no minification.

@addyosmani @deanhume thoughts on this?

**Comment by jeffposnick** [comment]
A `.*debug.*` version sounds reasonable to me. We could skip the async-to-generator transpilation step for those build, too, which should further aid in debugging and still work in the most recent Chrome release.

**Comment by gauntface** [comment]
Ok so I mis-understood our build flow.

All modules at the moment are producing *.min.js apart from the libraries that we had previously released which are using *.js but producing minified builds.

Should we move to *.min.js for all libraries with *.js for non-minified? This means we can have both options without breaking existing users of offline-analytics etc. Downside is developers won't get the minified version unless they switch over.

Alternatively we switch all to *.min.js and *.debug.js and force a choice from the developer.

**Comment by jeffposnick** [comment]
Sigh, yeah, the legacy stuff in this repo does complicate things. And then we also are neglecting the fact that we have the ES2015 module `.mjs` builds. And which build gets used as the `main`/`module` fields in `package.json` is worth thinking about, too.

So, given all that, I guess the safest/most flexible approach would be:

- Produce both minified and non-minified output with both `.js` and `.mjs` extensions. (So, 4 files total.)
- Set `main` to `build/project-name.min.js`.
- Set `module`/`jsnext:main` to `build/project-name.min.mjs`.

I can take this on, since it involves fiddling with some of the legacy stuff.

**Comment by gauntface** [comment]
If you could that would be great. I'm currently toying with CLI stuff to just get that started.
