### ISSUE TITLE
sw-lib: unclear that staleWhileRevalidate() is the new fastest()

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/sw-helpers#316]
**Library Affected**:
sw-lib

Couldn't find a reference to this in the docs during migration. It would be nice to be able to hint that the old name for this has been changed :)

**Comment by gauntface** [comment]
Yeah - this is a migration doc IMO.

**Comment by jpmedley** [comment]
They're not actually the same, right? You're just recommending replacing fastest with stale. I ask because it would seem that fastest would stop looking as soon as one returned, regardless of which, while stale may start out using the cached version, but will certainly replace it when the network call returns.

**Comment by gauntface** [comment]
It's more that staleWhileRevalidate will ALWAYS return from the cache, even if the network returned a response very quickly (May through a h2 push or http cache result). Where as fastest is a bit simpler, it'll race them, then return what ever is fastest.

Both will cache afterwards.

**Comment by jpmedley** [comment]
So, in what sense is staleWhileRevalidate() the new fastest()?

**Comment by gauntface** [comment]
Both serve from cache and continuously update the cached response.
