### ISSUE TITLE
Cache expiration manager

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#33]
**Library Affected**:
`sw-cache-expiration-manager`

**Issue or Feature Request Description**:
We can refactor the code that currently lives in `sw-toolbox` for cache expiration into a stand-alone `sw-helpers` library. I'd imagine that could be done in a way that would allow the module to be imported into `sw-toolbox` without any visible changes.

The module's interface might look like:

``` js
const cache1Manager = new goog.CacheExpirationManager({
  cacheName: 'cache1',
  policy: 'least-recently-used', // The default and only initial policy supported.
  maxSize: 10,
  maxAge: 24 * 60 * 60
});

// Create additional managers as needed.

// Call this within your `fetch` handler after you've added entries to 'cache1',
// or call it at service worker startup time.
cache1Manager.prune();
```

**Comment by addyosmani** [comment]
I would be interested in understanding how a cache expiration manager that works with the Cache API would interact with the browser's quota eviction rules and I/O pressure.  It otherwise sounds like a helper that would be super nice to have. Did you see this as being something that would work against the global Cache storage or would just work as part of Service Worker?

**Comment by jeffposnick** [comment]
See https://github.com/GoogleChrome/sw-helpers/tree/master/packages/sw-cache-expiration
