### ISSUE TITLE
add install info to docs pages

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/sw-helpers#331]
**Library Affected**:
all, probably

**Browser & Platform**:
n/a

**Issue or Feature Request Description**:
add an install section to the docs page (e.g. https://googlechrome.github.io/sw-helpers/reference-docs/stable/v0.0.13/module-sw-lib.html) for each module

**Comment by addyosmani** [comment]
I agree we should definitely be doing this. Thanks, @kaycebasques!

**Comment by jpmedley** [comment]
There are install instructions [here](https://googlechrome.github.io/sw-helpers/getting-started/sw-lib.html#main). I haven't made any moves to put them in a more logical place because of Matt's [remark in my draft](https://docs.google.com/document/d/1MC6pO3rF8g9op22YRD9thG2k-YWhOT1EUm5PkYXOhN0/edit#heading=h.2pkgvbx78pck) that he wanted to do some automation around this. 

(I just realized no ticket was ever opened on this, [so here](https://github.com/GoogleChrome/sw-helpers/issues/349).)

**Comment by jpmedley** [comment]
@gauntface @jeffposnick 

There's a [command-line flag](http://usejsdoc.org/about-including-readme.html) that will pull in the README. May need to do some tweaking, but this will prevent us from having to edit in two places.

 Implementation looks to be somewhere in the `node_modules` directory. I'm not sure how to precede. Please advise.

**Comment by gauntface** [comment]
@jpmedley please explain what you would like.

At one point we had the readme being the index page, someone has since moved away from that - what is it you are wanting and I'll look at it.

**Comment by jpmedley** [comment]
I may have misunderstood what this link does. Let's chat tomorrow.

**Comment by jpmedley** [comment]
This was addressed some time ago, as shown by this: https://googlechrome.github.io/sw-helpers/sw-cli.html#main

Closing.
