### ISSUE TITLE
sw-cli doesn't map /index.html => /

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/sw-helpers#334]
**Library Affected**:
sw-cli

**Browser & Platform**:
Node v7.7.2

**Issue or Feature Request Description**:
The manifest generation caches "/index.html", but doesn't cache "/". So reloading the top-level URL/domain/etc 404's because that resource doesn't exist.

Perhaps we could have a 'for-free' rewriting rule (e.g., if we see a request for "/" and we _have_ "/index.html", then serve that).

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

**Comment by addyosmani** [comment]
@jeffposnick I believe we discussed this briefly earlier today. Imo, this is going to be a common expectation and exploring some level of baked in rerouting might make sense.

**Comment by jeffposnick** [comment]
Equivalent logic in `sw-precache`: https://github.com/GoogleChrome/sw-precache/blob/776b05952bbdeebf9f35125e4f1b2a95f6e02d54/service-worker.tmpl#L141 (`directoryIndex` is configurable, and defaults to `index.html`).

**Comment by jeffposnick** [comment]
Untested, but one option for implementation could be modifying the logic in [`RequestWrapper.match()`](https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-runtime-caching/src/lib/request-wrapper.js#L152) to pass in some additional parameters to `cacheWillMatch`, along the lines of:

```js
if (this.plugins.has('cacheWillMatch')) {
  const plugin = this.plugins.get('cacheWillMatch')[0];
  cachedResponse = await plugin.cacheWillMatch(
    {request, cache, cachedResponse, matchOptions: this.matchOptions});
}
```

And then you could implement the desired behavior by passing in a plugin to the `RequestWrapper` used by the [precached URL handler in `sw-lib`](https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-lib/src/lib/sw-lib.js#L253):

```js
const indexFallback = async ({request, cache, cachedResponse, matchOptions}) => {
  // If we already have a cache hit, then just return that.
  if (cachedResponse) {
    return cachedResponse;
  }

  // Otherwise, try again with the indexHtmlString value.
  if request.url.endsWith('/') {
    const urlWithIndex = request.url + indexHtmlString;
    return cache.match(urlWithIndex, matchOptions);
  }
};

const cacheFirstHandler = this.strategies.cacheFirst({
  cacheName: this._revisionedCacheManager.getCacheName(),
  plugins: [{cacheWillMatch: indexFallback}],
});
```

I like that approach because it extends the existing `cacheWillMatch` lifecycle callback inside of `RequestWrapper` to make it more useful, and then it lets you inject that new fallback behavior only at the place within `sw-lib` where it would need to live.
