### ISSUE TITLE
Need way to change something in the root path

### ISSUE THREAD

**Issue by pbakaus** [GoogleChrome/sw-helpers#358]
**Library Affected**:
sw-build

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
My server maps /assets to /static and so I need a way to replace assets with static. `rootDirectory` doesn't work as it only accepts actual paths that exist.

**Comment by jeffposnick** [comment]
Cf. [`replacePrefix`](https://github.com/GoogleChrome/sw-precache#replaceprefix-string) in `sw-precache`.

**Comment by devnook** [comment]
+1

**Comment by gauntface** [comment]
cc @jeffposnick @addyosmani 

Using names [from this suggestion](https://github.com/GoogleChrome/sw-precache/issues/164), `modifyUrlPrefix` seems like a better name than `replacePrefix`, `stripPrefix` and `stringPrefixMulti`.

```
modifyUrlPrefix: {
  '/assets': '/static',
  '/dist/app': ''
}
```
Replace prefix is dropped and forces developer to define an empty string, `stripPrefix` and `stringPrefixMulti` are just morphed into the key value approach above.

**Comment by addyosmani** [comment]
I'm strongly in favor of just implementing `modifyUrlPrefix` instead of the trio of original versions of this from sw-precache. Looking at GitHub codesearch, usage of the older versions is low/not there and I don't see this breaking a huge number of folks. Having a migration path for the few that do need this should be sufficient.
