### ISSUE TITLE
Remove warmRuntimeCache, rename cacheRevisionedAssets?

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#370]
**Library Affected**:
*sw-lib*

Potentially controversial, but after observing developer confusion at the hackathon—https://github.com/GoogleChrome/sw-helpers/issues/353, but also confusion as to whether `warmRuntimeCache()` sets up routes (it doesn't) and whether it also deletes entries in the `activate` handler (it does)—I'm of the opinion that we should remove `warmRuntimeCache()` in favor of exposing the name of the default runtime cache (https://github.com/GoogleChrome/sw-helpers/issues/367) and encouraging developers who need that functionality to explicitly write:

```js
self.addEventListener('install', (event) => {
  const urls = [/* ... */];
  const cacheName = swLib.runtimeCacheName; // Or use your own name.
  event.waitUntil(caches.open(cacheName).then((cache) => cache.addAll(urls)));
});

// Setup runtime routes as needed.
```

At the same time, I'd like to see us rename `cacheRevisionedAssets()` to `precache()` or maybe `precacheAndRoute()` (since it also sets up routes), to steer developers down the path that adheres to best practices.

**Comment by jeffposnick** [comment]
Cf. https://github.com/GoogleChrome/sw-precache/issues/267

I'd like to avoid this confusion for users of `sw-lib` by only provider a single helper method that prepopulates a cache and encourages developers to follow the best practices of versioning their local assets.

**Comment by gauntface** [comment]
I've seen a number of people that have used sw-lib and since all examples use `cacheRevisionedAssets()`, developers will manually create a URL and a fake static revision - resulting in old stuff being served and then getting confused at why it hadn't updated :-1: 

Having both methods results in another source of confusion.

Here is the state of play:
1. Developers are confused by two caching options
1. Confusing how one sets up routes, the other does not
1. Importing the file manifest file needs to be revisioned - people aren't considerate of this
1. People arent' fully appreciating what the revision detail does.

A counter proposal:

1. Remove cacheRevisionedAssets from sw-lib
1. Keep warmRuntimeCache in sw-lib
1. Make sw-build output a JS file that contains the revision manifest, imports sw-precache revisions the assets and sets up the routes
1. Get developers to import this file.

Pros:
- Reduces caching options to a single entry
- seperating the caching strategies might clean up the routing set up concerns / confusion
- People are less likely to manually alter file manifests since it isn't supported by sw-lib.

Cons:
- seperating the caching strategies might further confuse the routing set up
- Importing this JS file needs to be revisioned - people aren't considerate of this

**Comment by jeffposnick** [comment]
Taking a step back and thinking about the big picture we hope to deliver with `sw-lib`: 

I feel that the ideal service worker that a developer using `sw-lib` ends up with will almost always use a cache-first strategy for versioned local assets, and will sometimes have runtime routes set up if there are cross-origin or media requests that can't be precached. That type of service worker has proved effective for both static sites and for SPAs following the App Shell + dynamic content model.

Equally important is that developers who use `sw-lib` should (almost) never end up with a service worker that leaves users stuck with out of date assets for an extended period of time.

Do you feel like that's the right big-picture goal for `sw-lib`? Should we be focusing on something else?

Once we have a model for what we're trying to steer developers towards, it might be easier to clarify which methods to expose and how we assume build-time integration will happen.

**Comment by gauntface** [comment]
I'd argue that `sw-helpers` is aiming to give developers the ideal service worker.

`sw-lib` is aiming to make it easy to write a service worker routing / caching strategy *Sadly plenty of wiggle room here*.

**Comment by jeffposnick** [comment]
My thinking was that `sw-lib` was how the large percentage of the developers out there would interact with the new codebase.

The other `sw-helpers` libraries will be useful for the small percentage of developers who would rather pick and choose what they use, or for the authors of other service worker tools to repurpose and wrap in their own higher-level interfaces.

`sw-helpers` as a whole has such a wide API surface that I find it hard to imagine a developer interacting with all of the individual modules and producing an ideal service worker. But a `sw-lib` with a tight, focused interface can (I hope!) fill that role.

So... thoughts from others? @addyosmani?

**Comment by gauntface** [comment]
Remove `warmRuntimeCache()` and rename `cacheRevisionedAssets()` -> `precache()` see if developers are ok with it (i.e. they don't mess themselves up by manually creating and editing the revision details).
