### ISSUE TITLE
Background Sync queue needs way to manual replay

### ISSUE THREAD

**Issue by prateekbh** [GoogleChrome/sw-helpers#384]
**Library Affected**:
sw-background-sync-queue

**Browser & Platform**:
all browsers

**Feature Request Description**:
There is a need for a manual way to replay all queued requests.
This could be also used in case of sw-offline-analytics where all the requests can be manually fired up on the `document ready` may be...

**Comment by prateekbh** [comment]
@jeffposnick @gauntface as I proposed one way to do this could look something like:
```js
if ('serviceWorker' in navigator) {
  navigator.serviceWorker.register('sw.js').then(reg=>{
    // This constant would replay every queued request.
    registration.sync.register('SW_BACGROUND_SYNC_REPLAY'); 
  });
}
```

**Comment by jeffposnick** [comment]
There's a typo in `BACGROUND`. But that seems fine to me in general.

Let's say that the replay request succeeds, and everything is removed from the queue. Is there a way of cancelling the "normal" `sync` event that would have fired at some point in the future anyway? Or would that `sync` event still trigger the handler, but the handler wouldn't do anything because the queue was empty?

**Comment by prateekbh** [comment]
@jeffposnick yeah, the sync event will still fire and nothing would happen as the queue would be empty

**Comment by addyosmani** [comment]
This sounds reasonable to me and noted as such over on https://github.com/GoogleChrome/sw-helpers/pull/386. Just landed - @prateekbh for any further testing items on that PR, do you want to go ahead and file an issue to track?
