### ISSUE TITLE
sw-build adding service worker to the manifest.js

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/sw-helpers#407]
**Library Affected**:
*sw-build*

[Here's where I'm seeing it.](https://github.com/jpmedley/redder2/tree/sw-build/app)

I don't know if this is a design or documentation issue. If you guys decide the later, just assign this ticket back to me.

**Comment by gauntface** [comment]
At the moment this is by design because as you pointed out in the chat - there is no way for sw-build to know what file is the service worker file.

Options to change this behavior:

1.) Add your service worker to globIgnores.
2.) Wait for changes where we'll replace the `cacheRevisionedAssets([])` with an array containing the manifest.

@jpmedley what do you think would be best?

**Comment by jpmedley** [comment]
Does the second require me to document anything? If it does, then option 1
means less work all around.

Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by addyosmani** [comment]
> 1.) Add your service worker to globIgnores.

Imo, this is the right call for now and sounds like it's in line with Joe's feedback above.
