### ISSUE TITLE
Revamp the defaults around opaque responses

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-helpers#78]
cc @addyosmani @jeffposnick 

**Library Affected**: sw-precache (Possibly some of the behavior modules as well)

**Browser & Platform**: All

**Issue or Feature Request Description**: How should we handle CORs / Bad requests?

This has been a common request / issue with developers using sw-toolbox (perhaps sw-precache as well). Arguments for and against which requests are cached and which aren't. Previously there was an option / config to define which status codes would be treated as valid status codes.

    // A regular expression to apply to HTTP response codes. Codes that match
    // will be considered successes, while others will not, and will not be
    // cached.
    successResponses: /^0|([123]\d\d)|(40[14567])|410$/

This breaks down to:

## 0 Opaque responses

**Good**: Works with CDN content from other domains.
**Bad**: Response may be bad and this means we could be serving up bad responses when a network 
response is available.

## 1XX Informational

> This class of status code indicates a provisional response, consisting only of the Status-Line and optional headers, and is terminated by an empty line. Since HTTP/1.0 did not define any 1xx status codes, servers must not send a 1xx response to an HTTP/1.0 client except under experimental conditions.

**Good**: ...
**Bad**: ...

Is this a common status code to use? When is this useful to cache?

## 2XX Success

> This class of status codes indicates the action requested by the client was received, understood, accepted and processed successfully.

**Good**: Extremely common and expected to be cached.
**Bad**: ...

## 3XX Redirection

> This class of status code indicates that further action needs to be taken by the user agent in order to fulfil the request. The action required may be carried out by the user agent without interaction with the user if and only if the method used in the second request is GET or HEAD. A user agent should not automatically redirect a request more than five times, since such redirections usually indicate an infinite loop.

**Good**: Can save a network trip from the server.
**Bad**: Redirect for auth may cause issues if cached and returned. Doesn't the `fetch` API handle redirects? Meaning that this should cache the final response rather than a 3XX redirect response?

## 401, 404, 405, 406, 407, 410 Client Error

> The 4xx class of status code is intended for cases in which the client seems to have erred. Except when responding to a HEAD request, the server should include an entity containing an explanation of the error situation, and whether it is a temporary or permanent condition. These status codes are applicable to any request method. User agents should display any included entity to the user.

401: Unauthorizaed
404: Not found
405: Method Not Allowed
406: Not Acceptable
407: Proxy Auth Required
410: Gone

**Good**: Handy if you want to cache a 404 page
**Bad**: If there is a server error and a 40X page is returned when it's not intended, this could lead to caching a bad response (bad in the eyes of the consumer of this library).

# Thoughts?

For default settings, my gut says that 2XX request should be cached, this is used for `Response.ok` and I believe is what the cache.addAll does use this or is being changed to do this.

For Opaque responses, I think it makes sense to cache them as well. Question is whether there are any negatives for caching this by default?

For 3XX and 4XX response I don't see the benefit of caching these.

Final comment: How should these be configured? Part of the options object for each module constructor that needs to cache requests? Should we stick to a regex?

**Comment by jeffposnick** [comment]
I don't know that there have been any cases where `sw-toolbox` caching a subset of 4xx errors was actually useful, and it just adds extra complexity, so I'm cool with not doing it by default in `sw-helpers`.

My vote is to have the `RequestWrapper` check for `response.ok || response.type === 'opaque'`, and if either of those is true, allowing the response to be added to the cache. (That's the logic that's [currently checked in](https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-runtime-caching/src/lib/request-wrapper.js#L143).)

This is different than the current `cache.addAll()` behavior, which as you mention, errs on the side of caution and will reject when it sees an opaque response.

There are a couple of tweaks we could make to add some nuance to the defaults and protect developers from inadvertently getting their caches into a bad state:

- Allow `opaque` responses to be cached when `RequestWrapper` is used inside of an explicit `Route`, but throw an error when `RequestWrapper` sees an opaque response inside of the [default handler](https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-routing/src/lib/router.js#L32).

- Allow `opaque` responses to be cached when `RequestWrapper` is used as part of a `staleWhileRevalidate` or `networkFirst` handler, but don't let them be cached when it's used as part of `cacheFirst`. The idea being that a bad opaque response will not get a chance to be updated when used with a `cacheFirst` strategy, so we should be extra cautious.

Regardless of what we decide the default behavior should be, we want to allow developers to explicitly override those defaults. I'm in favor of following the "behaviors" approach, and exposing a new `cacheWillUpdate` lifecycle callback that gets a chance to decide whether a response should or shouldn't be added to the cache. We could allow folks to override the defaults via a behavior class like:

```js
const requestWrapper = RequestWrapper({
  behaviors: [
    new CacheableResponseBehavior({
      statuses: [0, 200, 404]
    })
  ],
});
```

I could imagine some scenarios in which it would be useful to make `CacheableResponseBehavior` flexible enough so that it checked for something other than the response status, like only caching if there's a response header with a given value.

**Comment by gauntface** [comment]
Just grabbed the issues from this:

- https://github.com/GoogleChrome/sw-toolbox/issues/179
    - What no opaque responses
- https://github.com/GoogleChrome/sw-toolbox/issues/124
    - Wanted ability to precache non-cors requests.
- https://github.com/GoogleChrome/sw-precache/issues/18
    - Non-local resources for precache
- https://github.com/GoogleChrome/sw-toolbox/issues/131
    - Someone getting lost with cors / no-cors requests being cached and served
- https://github.com/GoogleChrome/sw-toolbox/issues/104
    - CORs oddity with a link tag.
- https://github.com/GoogleChrome/sw-toolbox/issues/38
    - Proposal to allow requests to be passed in that would allow custom setting of CORs modes

After talking with Jeff it feels like we are both agreed that **only** Cors and same origin requests should be allowed for `cacheRevisionedAssets()`, but opaque responses should not be allowed.

For `warmRuntimeCache()` there seems to be a few options:

## 1. Add requests instead of strings
    
Instead of just strings for URLs, allow the developers to define requests.

    cacheManager.warmRuntimeCache([
      new Request('https://example.com/whatsit', {
        mode: 'no-cors'
      }),
      new Request('https://example.com/whatsit-cors'),
      'https://example.com/whatis-still-cors',
      '/my-whatsit'
    ])

**Good**
- allows custom headers (We should allow this regardless?
- Super control for developer

**Bad**
- Some developers may dislike this - i.e. "The browser handles this for me every where else, why do I have to manage it here?"

## 2. Allow CORs and Non-CORs URLs

Allow both request types to be strings and fallback to non-cors request if the CORs request fails....

    cacheManager.warmRuntimeCache([
      'https://example.com/whatsit',
      'https://example.com/whatsit-cors',
      'https://example.com/whatis-still-cors',
      '/my-whatsit'
    ])

**Good**
- Much simpler for the developer

**Bad**
- Could get into a state where developer intend a CORs request, didn't get it and wouldn't want a no-CORs request....

**Comment by gauntface** [comment]
One last thing to discuss is do we throw an error if a request doesn't match?

**Comment by jeffposnick** [comment]
Re-opening to address recent discussions.

**Comment by gauntface** [comment]
We are going to allow opaque responses for caching strategies where the results of a bad response are limited.

**TODO**
- CacheOnly and CacheFirst strategies should throw when an opaque response is returned, including info on the valid caching strategies to use.
- StaleWhileRevalidate + NetworkFirst and NetworkOnly should be fine with caching and serving opaque responses

**Comment by jeffposnick** [comment]
I am going to perform a refactor of the `sw-cacheable-response` module, as per https://github.com/GoogleChrome/sw-helpers/issues/282, prior to implementing this change.
